### ISSUE TITLE
where is the plugin

### ISSUE THREAD

**Issue by JulianICE08935** [PowerNukkitX/AddsShields#1]
where is the plugin

because I only see the resource pack

![Screenshot_20230712-150531](https://github.com/PowerNukkitX/AddsShields/assets/106862754/b0a635ad-cc75-4344-9893-9de7ff8ab257)

**Comment by ReiyansCN** [comment]
You need to compile a copy of the plugin to run in PNX, and then get the corresponding texture package from the resource package address in the readme and put it on your PNX server
